### PR TITLE
Upgrade dotnet core version to 3.1

### PR DESCRIPTION
**Pull request by cdonges**

### CODE REVIEW

**Comment by Solen1985** [comment]
Hello. I am so sorry for seemingly abandoning the project. I really cannot find any time to work on it, at the moment. Hope all is well with you!

**Comment by cdonges** [comment]
It is what it is. I havent done much work on it recently either.

Just before Christmas the company I was working for went into liquidation.
I went for four interviews and mentioned this project in all of them. Three
of the interviewers loved civ and loved the project and I got three job
offers. I may have got offers without CivOne but I am sure it helped. Thank
you.

**Comment by Solen1985** [comment]
Wow, that's great! Just shows what a great game Civilization actually is... that people still love a 25+ year old game. In fact, I've used CivOne at a job interview myself last year. I'm really happy that our code has helped you this way.

My work has been so interesting for the past 10 months. I'm working from home now, and I only have to go to the office once every 2-3 weeks. I'm building a IoT platform for smart buildings, and I've got all kinds of devices stacked on a table at home, and wires running everywhere. Building everything in .NET Core. It's amazing, I'm getting everything I ask for and I've got total freedom on how I design the software and hardware. I am rarely able to limit my work time to 8 hours a day... most of the time I'm so immersed in work that I forget about the time...

But spending all day at home, working, probably makes it so that I cannot find the motivation to work on more code in my free time... without it feeling like work. I'm still trying to find a balance between work, family and leisure development... and of the three, family is more important and work is just necessary.

Hopefully I am able to eventually find a better balance for this and get back to seeing development as a hobby as well as work.

**Comment by cdonges** [comment]
Your work sounds pretty interesting.

Family and work will always come before a hobby project but I would suggest
you make a post on civ fanatics letting everyone know you are ok but busy.

**Comment by fire-eggs** [comment]
Life and work often interfere with side projects!

When I was working from home, I always found it hard to flip over to working on my own stuff. I wanted to switch gears and do something completely different!

As for CivOne, I did a big flurry of fixes for a little while, then got bogged down trying to tackle a larger piece [AI behavior]. So not much progress from me lately either!

In any case, a big "thank you!" for starting this project! 
All the best,
Kevin

**Pull request merged**
