### PR TITLE
Fix city resources getting reallocated automatically each time screen…

### PR DESCRIPTION
**Pull request by cdonges**
… opened and each new turn. Just do it when city size increases

https://github.com/SWY1985/CivOne/issues/448

Fix is really simple but seems to work ok. Can you take a look and let me know what you think please?

### CODE REVIEW

**Comment by jakebrown58** [comment]
Will this reshuffle everything on city growth?    If I recall, the original game keeps all the same tile, and then allocates the next-best tile after growth.   Looks like a move in the right direction though.

**Comment by SWY1985** [comment]
What happens when an enemy unit moves onto one of the resource tiles? That's the difficulty I had and that's why my workaround caused all the other issues.

**Comment by cdonges** [comment]
Ok, np. I will do some more work on this task.

**Comment by SWY1985** [comment]
You can easily test this by adding enemy units using the Debug menu. (need to enable that in the Setup screen)

**Comment by cdonges** [comment]
Yep, there is a decent chance I will be able to fix this over the weekend.

**Comment by cdonges** [comment]
I have made another really small change that I think fixes it. I think the issue is where it checks if any other cities are using a tile but doesn't exclude the current city so if a tile was being used it's considered invalid.

**Comment by SWY1985** [comment]
This appears to work, great job!

**Pull request merged**
