### PR TITLE
Game code separation extraction

### PR DESCRIPTION
**Pull request by uHappyLogic**
Game.cs class divided into separated code units (game loaders/savers/game state/logger)
Loading can be now tested without instantiating whole configuration

### CODE REVIEW

**Comment by SWY1985** [comment]
Sorry, I only just noticed the pull requests. It's going to take some time to review the code, but I noticed one that I would like you to change before I merge: Please do not use the 'var' keyword. Use strongly type variables only.

**Comment by uHappyLogic** [comment]
Every var is now replaced by explicit variable type definition.
Changes made after creation of this pull request are merged.
Additionally bug was found and fixed

**Comment by SWY1985** [comment]
First of all, I am happy that you're trying to contribute, and I spent some time writing this because you also spend considerable time making these changes. I will explain why I can not merge this code, if you have any questions or if you disagree, feel free to discuss them.

I tried to merge into a seperate branch but that didn't work so the merge was committed to master.
On first try, I was hit by a NullReferenceException from logOperation in Logger.Log. I reverted the changes immediately for later review.

There's a couple of coding guidelines that you may have overlooked. Sorry, I have not documented them exactly, I will spend some time doing that. Here's a short summary:

- Use tabs instead of spaces (this would have been enforced and visible to you if you had uses Visual Studio Code)
- Variable naming: Public and Internal use PascalCasing, local variables and method arguments use camelCase, private variables use _underscoreCamelCase, constants use SCREAMING_CAPS
- System namespaces go before project namespaces, not like you did here: https://github.com/uHappyLogic/CivOne/blob/09a6b881ab25121df2ee6eefd3824e5a1a712931/src/Map.cs
- Do not waste space, a single empty line is enough. We do not need an empty line after at the start or end of a bracket, files do not need to end with a new line
- Function declarations can go on a single line
- I know I'm going against some coding guidelines with this, but in this project, the constructor is placed at the end of the file, only optionally followed by a Dispose function or a destructor

Then, the changes. Can you explain to me, why do we need a static Logger class? What's wrong with the old logging code?
I also don't really like that everything is suddenly refering to a GameState object. I understand the Game class is getting a bit complicated, but splitting it into another object is not a solution.

I'm sorry if my criticism is putting you off, I don't mean to do that, but this commit changes too much that I don't think needs changing. The code changes you made do not fit with the existing code style. I also think your changes make the code more complex, rather than simpler.

Perhaps, if you want to contribute to CivOne, it's better to start with a couple of bug fixes first. I am totally open to bug fixes, feature implementations and code improvements. But this commit changes too much that has nothing to do with game save/load.

**Comment by uHappyLogic** [comment]
Thank you for detailed explanation. Don’t think I am angry or something like that, because I’m not, and please let me explain myself. I will address things in order you raised them in your comment.

First thing “NullReferenceException „. To be honest I tested game very carefully, including multiple game saves and loads and “it worked”. I suspect that you are not using windows for testing. Of course this is solely my fault, if I had test game under other platform (like Ubuntu) I will catch this immediately.
As you can see in file [runtime/win32/src/Program.cs] line 21 proper logger is assigned to static logger class, and now I realized that it is not done for all OS configurations.
About formatting issues mentioned by You in next section. I am using Visual Studio Community 2017 and I thought that this IDE saves my tabs as tabs, not as spaces. I suspect that it is matter of configuration.
About other issues, in my defense, I somehow indoctrinated by few years in IT industry with some approaches like public members first, private last. But I respect that this is your project and rules should be followed, so I will write code according to your guidelines (it will be helpful if you will place somewhere on project page or in git repository some document with such guidelines).

Reason behind creation of static logger class (which is in fact proxy to some interface implementation) is code decoupling which make testing easier. For now it is very hard to create unit tests mainly because code is tightly coupled. For example with logging approach proposed by me it is easy to provide some DummyLogger by Logger.SetLogger(DummyLogger.Log); , without that abstraction test have to depend on real logger implementation.

And least but not last. Is this changes made code more complex. My answer is yes, these changes can be seen like that. But adding abstraction layers to code will enable easy unit testing. And using unit tests always pays off (I will even say that unit testing is crucial to every project in which changes are made). Also you mentioned that these changes has to do nothing with game load/save. I can agree that implementing new game save/load system can be done without these changes, but with GameState (which main purpose is to be storage with only initialization logic) is easier to create such system rather than operating on Game class which consist many things related to actual game logic.
To be honest, I hoped that these changes will be merged into the upstream master, but even when not I think that work which I put into making this changes is not lost. I learned many things about project and I hope that this knowledge will be useful in later time as I will continue in my tries to contribution to this project.

**Comment by SWY1985** [comment]
Thank you for your reply. I'm glad you understand my points.
The NullReferenceException did, in fact, happen on a Windows machine. I guess something else has gone wrong.

I will do my best to make a wiki page with coding guidelines, I'm sorry, that should've been done already.

As someone who's never been convinced about unit testing, I may be prejudiced. I strongly believe that, if the code can not be accessed for unit testing, it's better to not use unit testing. In no way should code be made more verbose in order to be able to run unit tests.
Now, I've added the Unit Test project, because I love to be proven wrong about unit testing. I know a lot of people swear by it. I think in order for unit testing to work, the unit test project should at least implement the IRuntime interface and deliver some input to the game. When I find the time, I will try to create an example of what I mean.
Just for your information, the CivOne assembly has already been modified so the Unit Test project can access all internal variables and functions. That should make things easier.

I am inspired by your code, I'm trying to give my own spin to getting the game data out of the Game class so you (and other people) can create a load/save plugins in the future.
At the moment, I'm adding code to the CivOne API that will provide a way to get game save data loaded into the game and saved from the game, without having to break up the game internals too much.
I will make an implementation of this by (finally) getting near complete compatibility with the original game load/save game files. (issues #153 and #248) That should have been the priority from the start I think. I hope that I can finish most of this code this week, and I really hope you'll have a look at that code and see if it works for you.

Thank you for understanding and I'm looking forward to your future contributions.

**Pull request merged**
