### PR TITLE
Fix veteran attack strength calculation and let defending units gain veteran status upon winning

### PR DESCRIPTION
**Pull request by AlexFolland**

### CODE REVIEW

**Comment by SWY1985** [comment]
Thank you for this.

**Comment by AlexFolland** [comment]
I'm glad I could help!

**Comment by SWY1985** [comment]
I got a compile error: The compile could not convert "1.5" from double to int. I've created an alternative solution.

**Comment by AlexFolland** [comment]
Okay.  Thanks.

**Pull request merged**
