### PR TITLE
Add basic functionality to  bribe unit with diplomat

### PR DESCRIPTION
**Pull request by cdonges**

### CODE REVIEW

**Comment by cdonges** [comment]
I didn't know that. Do you know what message it displays? Otherwise I can
find out from the original

On 4 Mar. 2018 9:23 am, "Jake Brown" <notifications@github.com> wrote:

*@jakebrown58* commented on this pull request.

Don't forget, you can't bribe a unit whose government is Democracy.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SWY1985/CivOne/pull/456#pullrequestreview-100989977>,
or mute the thread

**Comment by SWY1985** [comment]
I'm not certain, but I don't think a diplomat disappears after bribing a unit, does it?

**Comment by cdonges** [comment]
I think you are right. I will check and make the change.

**Comment by cdonges** [comment]
I have fixed the diplomat being destroyed.

I have tried to replicate not being able to bribe a unit from a democrcy in dos civ and I haven't been able to do it yet. I will have another look tomorrow. 

I can't find a screenshot of how it looks either :(.

**Comment by jakebrown58** [comment]
i gave it a look, but couldn't find anything on it.  i swear that was true though!

i can try another test game tonight.   IIRC, the option was not shown, and you couldn't move your diplomat to the enemy tile (no movement spent) if they were unbribable.

**Comment by cdonges** [comment]
I tried editing a save game and made all my opponents democracy then I
tried bribing a unit and it went through no problem. It was my first time
using the save game editor though and I could have been doing something
wrong.

**Comment by jakebrown58** [comment]
hm.   maybe it's version specific.    like your peppa pig icon, BTW.

**Comment by cdonges** [comment]
Not sure. I am happy to put it in either way - I just need to know what the
behavior should be. If there is a message or if it just stops the diplomat
moving.

My kids say I look like daddy pig...

**Comment by jakebrown58** [comment]
I'd say ignore anything I said about Democracy until we can confirm it works that way in the original.

**Comment by cdonges** [comment]
PR should be good to go then :)

**Comment by SWY1985** [comment]
Thank you for your contribution. 👍

**Comment by cdonges** [comment]
No problem. First of many hopefully. :)

**Pull request merged**
